# Generated by Django 4.1 on 2023-07-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(null=True, to='articles.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
