# Generated by Django 4.1 on 2023-08-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='top_image',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
