# Generated by Django 4.1 on 2023-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_description_article_top_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
